pct/login/urls.py
from django.urls import path,include
from login import views


app_name = 'login'

urlpatterns = [
    path('', views.user_login, name='user_login'),

]

pct/pct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='main'),
    path('manager/',include('login.urls'),name='manager'),
    path('manager/dashboard/',include('dashboard.urls'),name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'),name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pct/login/models.py
from django.db import models

# Create your models here.

pct/login/views.py
from django.contrib.auth import authenticate, logout, login
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request) :
    return render(request,"login/backend-html")

def user_login(request) :
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username =='admin' and password=='admin':
            return HttpResponseRedirect(reverse('dashboard:theatre-manager-view'))
        else :
            return HttpResponse("Login Failed")

    else :
        return render(request,'login/backend-login.html')

pct/templates/login/backend-login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> login Page</title>
    <!--External Links-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <!-- custom style sheet -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<!-- This body of the front page -->
<body style="background-color:rgb(236, 235, 235)">
    <div class="container login-container">

            <div class="col-md-8 login-form-2">
                <h2 style="letter-spacing : 1px;">Login Panel</h2>
                <form action="{% url 'login:user_login' %}" method="POST">
                    <div class="form-group">
                        <label for="username">Your Username</label>
                        <input type="text" class="form-control"  value="" id="username" name="username" />
                    </div>
                    <div class="form-group">
                        <label for="password">Your Password</label>
                        <input type="password" class="form-control" value="" id="password" name="password" />
                    </div></br>
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="submit" class="btnSubmit" value="Login" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>