pct/dashboard/urls.py
from django.urls import path,include,re_path
from dashboard import views
app_name='dashboard'
urlpatterns = [
    path('', views.theatre_manager_view.as_view(), name='theatre-manager-view'),
    path('theatre-view/',views.theatre_view.as_view(),name="theatre-view"),
    path('screen-view/',views.screen_view.as_view(),name="screen-view"),
    path('show-view/',views.show_view.as_view(),name="show-view"),
    path('movie-view/',views.movie_view.as_view(),name="movie-view"),
    path('theatre-manager-create/',views.theatre_manager_create.as_view(),name="theatre-manager-create"),
    path('theatre-create/',views.theatre_create.as_view(),name="theatre-create"),
    path('screen-create/',views.screen_create.as_view(),name="screen-create"),
    path('show-create/',views.show_create.as_view(),name="show-create"),
    path('movie-create/',views.movie_create.as_view(),name="movie-create"),
    re_path(r'^theatre-manager-delete/(?P<pk>\d+)/$',views.theatre_manager_delete_view.as_view(),name="theatre-manager-delete-view"),
    re_path(r'^theatre-delete/(?P<pk>\d+)/$',views.theatre_delete_view.as_view(),name="theatre-delete-view"),
    re_path(r'^screen-delete/(?P<pk>\d+)/$',views.screen_delete_view.as_view(),name="screen-delete-view"),
    re_path(r'^show-delete/(?P<pk>\d+)/$',views.show_delete_view.as_view(),name="show-delete-view"),
    re_path(r'^movie-delete/(?P<pk>\d+)/$',views.movie_delete_view.as_view(),name="movie-delete-view"),
    re_path(r'^theatre-manager-detail/(?P<pk>\d+)/',views.theatre_manager_detail_view.as_view(),name="theatre-manager-detail-view"),
    re_path(r'^theatre-detail/(?P<pk>\d+)/',views.theatre_detail_view.as_view(),name="theatre-detail-view"),
    re_path(r'^screen-detail/(?P<pk>\d+)/',views.screen_detail_view.as_view(),name="screen-detail-view"),
    re_path(r'^show-detail/(?P<pk>\d+)/',views.show_detail_view.as_view(),name="show-detail-view"),
    re_path(r'^movie-detail/(?P<pk>\d+)/',views.movie_detail_view.as_view(),name="movie-detail-view"),

]

pct/pct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='main'),
    path('manager/',include('login.urls'),name='manager'),
    path('manager/dashboard/',include('dashboard.urls'),name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'),name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pct/dashboard/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator
from django import forms
from django.contrib.auth.models import User


# Create your models here.
class theatre_manager(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField()
    address=models.CharField(max_length=1000)
    phone=models.BigIntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dashboard:theatre-manager-view")


class theatre(models.Model) :
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    theatre_manager = models.ForeignKey(theatre_manager,related_name="theatre",on_delete=models.CASCADE)

    def __str__(self) :
        return self.name

    def get_absolute_url(self) :
        return reverse("dashboard:theatre-view")

class screen(models.Model) :
    name = models.CharField(max_length=20)
    no_of_rows = models.IntegerField(validators=[MaxValueValidator(75)])
    no_of_columns = models.IntegerField(validators=[MaxValueValidator(50)])
    theatre = models.ForeignKey(theatre,related_name="screen",on_delete=models.CASCADE)

    def __str__(self) :
        return "{x} {y}".format(x=self.name,y=self.theatre.name)

    def get_absolute_url(self) :
        return reverse("dashboard:screen-view")


class movie(models.Model) :
    name = models.CharField(max_length=50)
    hero = models.CharField(max_length=30)
    heroine = models.CharField(max_length=30)
    director = models.CharField(max_length=30)
    genre = models.CharField(max_length=150,help_text='Seperate genre with spaces',null=True)
    language = models.CharField(max_length=150,help_text='Seperate language with spaces',null=True)
    description = models.TextField(default='Description Text')
    release_date = models.DateField(help_text='mm/dd/yyyy')
    runtime_in_minutes = models.IntegerField(validators=[MaxValueValidator(200)])
    trailer = models.CharField(max_length=1000)
    thumbnail_image = models.ImageField(upload_to='movie_thumbs')
    slideshow_image = models.ImageField(upload_to='movie_thumbs',default='true')

    def __str__(self) :
        return self.name

    def get_absolute_url(self) :
        return reverse("dashboard:movie-view")

class show(models.Model) :
    date = models.DateField()
    time = models.TimeField()
    price = models.IntegerField()
    screen = models.ForeignKey(screen,related_name="show_screen",on_delete=models.CASCADE)
    theatre = models.ForeignKey(theatre,related_name="show_theatre",on_delete=models.CASCADE)
    movie = models.ForeignKey(movie,related_name="show_movie",on_delete=models.CASCADE)

    def __str__(self) :
        return "Date : {}".format(self.date)

    def get_absolute_url(self) :
        return reverse("dashboard:show-view")


class User1(models.Model):
    # ['username', 'first_name', 'last_name', 'email', ]
    username=models.CharField(max_length=20)
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    email=models.EmailField()
    password=models.CharField(max_length=20)

pct/dashboard/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, ListView, CreateView, DeleteView, DetailView
from . import models
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User



class theatre_manager_create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    fields = '__all__'
    model = models.theatre_manager
    template_name = 'dashboard/theatre_manager_form.html'


class theatre_manager_view(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    context_object_name = 'theatre_managers'
    model = models.theatre_manager
    template_name = 'dashboard/theatre_manager_view.html'
    permission_required = 'dashboard.theatre_manager.can_view_theatre_manager'


class theatre_manager_detail_view(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    context_object_name = 'theatre_managers'
    model = models.theatre_manager
    template_name = 'dashboard/theatre_manager_detail_view.html'
    permission_required = 'dashboard.theatre_manager.can_view_theatre_manager'




class theatre_manager_delete_view(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    context_object_name = 'theatre_managers'
    model = models.theatre_manager
    success_url = reverse_lazy("dashboard:theatre-manager-view")
    permission_required = 'dashboard.theatre_manager.can_delete_theatre_manager'




class theatre_create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    fields = '__all__'
    model = models.theatre



class theatre_view(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    context_object_name = 'theatre'
    model = models.theatre
    template_name = 'dashboard/theatre_view.html'
    permission_required = 'dashboard.theatre.can_view_theatre'


class theatre_detail_view(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    context_object_name = 'theatre'
    model = models.theatre
    template_name = 'dashboard/theatre-detail-view.html'
    permission_required = 'dashboard.theatre.can_view_theatre'





class theatre_delete_view(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    context_object_name = 'theatre'
    model = models.theatre
    success_url = reverse_lazy("dashboard:theatre-view")
    permission_required = 'dashboard.theatre.can_delete_theatre'




class screen_create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    fields = '__all__'
    model = models.screen



class screen_view(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    context_object_name = 'screen'
    model = models.screen
    template_name = 'dashboard/screen_view.html'
    permission_required = 'dashboard.screen.can_view_screen'


class screen_detail_view(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    context_object_name = 'screen'
    model = models.screen
    template_name = 'dashboard/screen-detail-view.html'
    permission_required = 'dashboard.screen.can_view_screen'




class screen_delete_view(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    context_object_name = 'screen'
    model = models.screen
    success_url = reverse_lazy("dashboard:screen-view")
    permission_required = 'dashboard.screen.can_delete_screen'




class show_create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    fields = '__all__'
    model = models.show



class show_view(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    context_object_name = 'show'
    model = models.show
    template_name = 'dashboard/show_view.html'
    permission_required = 'dashboard.show.can_view_show'


class show_detail_view(LoginRequiredMixin, DetailView):
    context_object_name = 'show'
    model = models.show
    template_name = 'dashboard/show-detail-view.html'
    permission_required = 'dashboard.show.can_view_show'





class show_delete_view(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    context_object_name = 'show'
    model = models.show
    success_url = reverse_lazy("dashboard:show-view")
    permission_required = 'dashboard.show.can_delete_show'




class movie_create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    fields = '__all__'
    model = models.movie
    permission_required = 'dashboard.movie.can_add_movie'


class movie_view(PermissionRequiredMixin, ListView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'dashboard/movie_view.html'
    permission_required = 'dashboard.movie.can_view_movie'


class movie_detail_view(PermissionRequiredMixin, DetailView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'dashboard/movie-detail-view.html'
    permission_required = 'dashboard.movie.can_view_movie'





class movie_delete_view(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    context_object_name = 'movie'
    model = models.movie
    success_url = reverse_lazy("dashboard:movie-view")
    permission_required = 'dashboard.movie.can_delete_movie'

pct/dashboard/templates/dashboard/layout.html
<!DOCTYPE html>
<html lang="en">
        {% load static %}
<head>
  <title>Dashboard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--External Links-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{%static 'js/bootstrap.min.js' %}"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <!-- custom style sheet -->

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>

	<body style="background-color:rgb(236, 235, 235);"> <!-- Background color of the website  can be changed here -->


<div class="sidenav hidden-sm hidden-xs" id="dashboard_sidenav">
    <h4><strong>Welcome !</strong></h4>

  <button class="dropdown-btn"><i class="fas fa-couch"></i> &nbsp;<strong> Theatre Management </strong> &nbsp;<i class="fa fa-caret-down"></i></button>
    <div class="dropdown-container">
        <a href="{% url 'dashboard:theatre-manager-view' %}"><strong>Theatre Managers</strong></a>
      <a href="{% url 'dashboard:theatre-view' %}"><strong>Theatres</strong></a>
      <a href="{% url 'dashboard:screen-view' %}"><strong>Screens</strong></a>
      <a href="{% url 'dashboard:show-view' %}"><strong>Shows</strong></a>

    </div>

  <a href="{% url 'dashboard:movie-view' %}"><i class="fas fa-film"></i> &nbsp;<strong> Movie Management</strong> </a>

  <h5 class="version"><strong>Version 1.0</strong></h5>
</div>


<!--mobile navbar-->


<div class="topnav" id="myTopnav" style="margin-bottom:20px;">
<div class="hidden-lg hidden-md">

</div>
</div>

<script>
function myFunction() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
        x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}

var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}


</script>


<!--end of mobile navbar-->


<div class="container">
  <div class="jumbotron">

    {% block content %}
    {% endblock %}

  </div>
</div>

</body>
</html>

pct/dashboard/templates/dashboard/movie-detail-view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

h4 {
    letter-spacing: 2px;
    padding-bottom: 10px;
    font-size: 17px;
}
.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

</style>

<h3><strong>
    Details of {{ movie.name }}
  </strong></h3></br>

  <h4><strong>ID : </strong>{{ movie.id }}</h4>
  <h4><strong>Name : </strong>{{ movie.name }}</h4>
  <h4><strong>Hero : </strong>{{ movie.hero }}</h4>
  <h4><strong>Heroine : </strong>{{ movie.heroine }}</h4>
  <h4><strong>Director : </strong>{{ movie.director }}</h4>
  <h4><strong>Release Date : </strong>{{ movie.release_date }}</h4>
  <h4><strong>Movie Runtime : </strong>{{ movie.runtime_in_minutes }}min</h4>
  <h4><strong>Show Information : </strong>{{ movie.description }}</h4>
<h4><strong>Trailer :</strong> <a href="{{ movie.trailer }}">Click here</a></h4>





  <a href="{% url 'dashboard:movie-view' %}"><button class="btn btn-primary">Back</button></a>

{% endblock %}

pct/dashboard/templates/dashboard/movie_confirm_delete.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>

h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

.btn-primary:hover {
    background-color: rgb(7, 7, 218);
}

.btn-danger {
    border-radius: 2rem;
    width: 150px;
    font-weight: 700;
}

</style>

    <h3><strong>Delete {{ movie.name }} ?</strong></h3></br>
    <div class="row">
        <div class="col-lg-3">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes, Delete" class="btn btn-danger">
        </form>
        </div>
        <div class="col-lg-9">
            <a href="{% url 'dashboard:movie-view' %}"><button class="btn btn-primary">No, Cancel</button></a>
        </div>
    </div>

{% endblock %}

pct/dashboard/templates/dashboard/movie_view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

td {
  padding: 1% !important;
  font-weight: 400;
  color : rgb(0,0,0);
  text-align: center;
}

th {
  text-align: center;
}

.btn-success,.btn-danger,.btn-primary {
  border-radius: 5rem;
  background-color: rgb(48, 42, 56);
  border-color: rgb(48, 42, 56);
}

.btn-success:hover,.btn-danger:hover,.btn-primary:hover {
  background-color: rgb(0,0,0);
  border-color: rgb(0,0,0);
}

.btn-default {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
  border-radius: 2rem;
  width: 180px;
  font-weight: 700;
  float : right;
  }

.btn-default:hover {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
}

.panel-default{
  background-color: rgb(7, 7, 218);
}

</style>

<h3><strong>
  Movies <br>
<br>

<div class="row">
    {% for mo in movie %}
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <img src="{{ mo.thumbnail_image.url }}" width="100%" height="100%" />
            </div>
            <div class="panel-body">
                <div class="container" style="margin-left: 8%;">
                <a href="{% url 'dashboard:movie-detail-view' pk=mo.id %}"><button class="btn btn-primary"><i class="fas fa-eye"></i></button></a></i></button></a> &nbsp; &nbsp; <a href="{% url 'dashboard:movie-delete-view' pk=mo.id %}"><button class="btn btn-danger"> <i class="fas fa-trash"></i></button></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

pct/dashboard/templates/dashboard/screen-detail-view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

h4 {
    letter-spacing: 2px;
    padding-bottom: 10px;
    font-size: 17px;
}
.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

</style>

<h3><strong>
    Details of {{ screen.name }}
  </strong></h3></br>

  <h4><strong>ID : </strong>{{ screen.id }}</h4>
  <h4><strong>Name : </strong>{{ screen.name }}</h4>
  <h4><strong>No of Rows : </strong>{{ screen.no_of_rows }}</h4>
  <h4><strong>No of Columns : </strong>{{ screen.no_of_columns }}</h4>
  <h4><strong>Belongs to : </strong>{{ screen.theatre.name }} Theatre</h4>
  <h4><strong>Managed By : </strong>{{ screen.theatre.theatre_manager.name }}</h4></br>



  <a href="{% url 'dashboard:screen-view' %}"><button class="btn btn-primary">Back</button></a>

{% endblock %}

pct/dashboard/templates/dashboard/screen_view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

td {
  padding: 1% !important;
  font-weight: 400;
  color : rgb(0,0,0);
  text-align: center;
}

th {
  text-align: center;
}

.btn-success,.btn-danger,.btn-primary {
  border-radius: 5rem;
}

.btn-primary {
  background-color: rgb(7, 7, 218);
}

.btn-default {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
  border-radius: 2rem;
  width: 180px;
  font-weight: 700;
  float : right;
  }

.btn-default:hover {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
}

</style>

<h3><strong>
  Screens <br>
<br>


<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Rows</th>
        <th>Cols</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for sr in screen %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ sr.name }}</td>
        <td>{{ sr.no_of_rows }}</td>
        <td>{{ sr.no_of_columns }}</td>
        <td><a href="{% url 'dashboard:screen-detail-view' pk=sr.id %}"><button class="btn btn-primary"><i class="fas fa-eye"></i></button></a><a href="{% url 'dashboard:screen-delete-view' pk=sr.id %}"><button class="btn btn-danger"> <i class="fas fa-trash"></i></button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

pct/dashboard/templates/dashboard/show-detail-view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

h4 {
    letter-spacing: 2px;
    padding-bottom: 10px;
    font-size: 17px;
}
.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

</style>

<h3><strong>
    Details of {{ show.screen.name }} with Show Id {{ show.id }}
  </strong></h3></br>

  <h4><strong>ID : </strong>{{ show.id }}</h4>
  <h4><strong>Date & Time : </strong>{{ show.date_time }}</h4>
  <h4><strong>Price : </strong>{{ show.price }}</h4>
  <h4><strong>Screen Name : </strong>{{ show.screen.name }}</h4>
  <h4><strong>Belongs to : </strong>{{ show.theatre.name }} Theatre</h4>
  <h4><strong>Managed By : </strong>{{ show.theatre.theatre_manager.name }}</h4></br>



  <a href="{% url 'dashboard:show-view' %}"><button class="btn btn-primary">Back</button></a>

{% endblock %}

pct/dashboard/templates/dashboard/show_view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

td {
  padding: 1% !important;
  font-weight: 400;
  color : rgb(0,0,0);
  text-align: center;
}

th {
  text-align: center;
}

.btn-success,.btn-danger,.btn-primary {
  border-radius: 5rem;
}

.btn-primary {
  background-color: rgb(7, 7, 218);
}

.btn-default {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
  border-radius: 2rem;
  width: 180px;
  font-weight: 700;
  float : right;
  }

.btn-default:hover {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
}

</style>

<h3><strong>
  Shows
</strong></h3></br>



<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Date & Time</th>
        <th>Movie</th>
        <th>Price</th>
        <th>Theatre Name</th>
        <th>Screen Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for sh in show %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ sh.date }} {{ sh.time }}</td>
        <td>{{ sh.movie.name }}</td>
        <td>{{ sh.price }}</td>
        <td>{{ sh.theatre.name }}</td>
        <td>{{ sh.screen.name}}</td>
        <td><a href="{% url 'dashboard:show-detail-view' pk=sh.id %}"><button class="btn btn-primary"><i class="fas fa-eye"></i></button></a> </button></a> &nbsp;<a href="{% url 'dashboard:show-delete-view' pk=sh.id %}"><button class="btn btn-danger"> <i class="fas fa-trash"></i></button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

pct/dashboard/templates/dashboard/theatre_manager_view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

td {
  padding: 1% !important;
  font-weight: 400;
  color : rgb(0,0,0);
  text-align: center;
}

th {
  text-align: center;
}

.btn-success,.btn-danger,.btn-primary {
  border-radius: 5rem;
}

.btn-primary {
  background-color: rgb(7, 7, 218);
}

.btn-default {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
  border-radius: 2rem;
  width: 180px;
  font-weight: 700;
  float : right;
  }

.btn-default:hover {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
}

</style>

<h3><strong>
  Theatre Managers<br>
  <br>




<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone No</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>

      {% for theatre in theatre_managers %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ theatre.name }}</td>
        <td>{{ theatre.email }}</td>
        <td>{{ theatre.phone }}</td>
        <td><a href="{% url 'dashboard:theatre-manager-detail-view' pk=theatre.id %}"><button class="btn btn-primary"><i class="fas fa-eye"></i></button></a> &nbsp; <a href="{% url 'dashboard:theatre-manager-delete-view' pk=theatre.id %}"><button class="btn btn-danger"> <i class="fas fa-trash"></i></button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

pct/dashboard/templates/dashboard/theatre_view.html
{% extends 'dashboard/layout.html' %}

{% block content %}

<style>
h3 {
        color : rgb(7, 7, 218);
        margin-top : -20px;
    }

td {
  padding: 1% !important;
  font-weight: 400;
  color : rgb(0,0,0);
  text-align: center;
}

th {
  text-align: center;
}

.btn-success,.btn-danger,.btn-primary {
  border-radius: 5rem;
}

.btn-primary {
  background-color: rgb(7, 7, 218);
}

.btn-default {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
  border-radius: 2rem;
  width: 180px;
  font-weight: 700;
  float : right;
  }

.btn-default:hover {
  color: rgb(255, 255, 255);
  background-color: rgb(7, 7, 218);
}

</style>

<h3><strong>
  Theatres<br>
<br>



<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Phone No</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for th in theatre %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ th.name }}</td>
        <td>{{ th.phone }}</td>
        <td><a href="{% url 'dashboard:theatre-detail-view' pk=th.id %}"><button class="btn btn-primary"><i class="fas fa-eye"></i></button></a><a href="{% url 'dashboard:theatre-delete-view' pk=th.id %}"><button class="btn btn-danger"> <i class="fas fa-trash"></i></button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}