pct/main/urls.py
from django.urls import path,include,re_path
from main import views
from .views import login,LogoutView
app_name = 'main'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('',views.user_signup,name="signup"),
    path('movies/', views.movies.as_view(), name='movies'),
    path('search/', views.search, name='search'),
    path('login/', views.login),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/<int:pk>/<str:user>/', views.account.as_view(), name='account'),
    re_path(r'^accounts/(?P<pk>\d+)/(?P<user>[\w.@+-]+)/$', views.account.as_view(), name="accounts"),
    re_path(r'^accounts-update/(?P<pk>\d+)/',views.account_update.as_view(),name="accounts-update"),
    re_path(r'^accounts-delete/(?P<pk>\d+)/',views.account_delete.as_view(),name="accounts-delete"),
    re_path(r'^movie-detail/(?P<pk>\d+)/',views.movie_detail_view.as_view(),name="movie-detail-view"),
    re_path(r'^theatre-list/(?P<pk>\d+)/',views.movie_booking_theatre.as_view(),name="movie-booking-theatre"),
    re_path(r'^booking/(?P<pk>\d+)/',views.show_details.as_view(),name="movie-booking"),
    re_path(r'^book-ticket/(?P<pk>\d+)/(?P<id>\d+)',views.book_ticket,name="book-ticket"),
    re_path(r'^booked/(?P<pk>\d+)/',views.booked.as_view(),name="booked"),
    re_path(r'^cancel/(?P<pk>\d+)/',views.cancel_ticket,name="cancel_ticket"),
]

pct/pct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='main'),
    path('manager/',include('login.urls'),name='manager'),
    path('manager/dashboard/',include('dashboard.urls'),name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'),name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pct/main/models.py
from django.db import models
from django.forms import ModelForm
from dashboard.models import show
from django.contrib.auth.models import User



TICKET_STATUS_CHOICES=(
    (1,'AVAILABLE'),
    (2,'BLOCKED'),
    (3,'BOOKED')
)

class booking1(models.Model):

    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField(null=False)
    phonenumber=models.IntegerField(default=None)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    row_num = models.PositiveSmallIntegerField(null=False, blank=False)
    col_num = models.PositiveSmallIntegerField(null=False, blank=False)
    show = models.ForeignKey(show, related_name="booking1_movie", null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="booking1_show", null=False, default=None, on_delete=models.CASCADE)
    status = models.IntegerField(choices=TICKET_STATUS_CHOICES, default=1)
    session = models.CharField(blank=False, null=False, max_length=200)

    def __str__(self):
        return str(self.phonenumber)
    class Meta:
        unique_together=('show','row_num','col_num')



class TicketsForm(ModelForm):
    class Meta:
        model = booking1
        fields = ['name','age','phonenumber','col_num','row_num',]

pct/main/forms.py
from django import forms

# username=models.CharField(max_length=20)
#     first_name=models.CharField(max_length=20)
#     last_name=models.CharField(max_length=20)
#     email=models.EmailField()
#     password=models.CharField(max_length=20)
class registertable(forms.Form):
    username=forms.CharField(min_length=6,max_length=15)
    first_name=forms.CharField(min_length=6,max_length=15)
    Last_name=forms.CharField(min_length=6,max_length=15)
    email=forms.EmailField()
    password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)
    confirm_password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)

class logint(forms.Form):
    username=forms.CharField(min_length=6,max_length=15)
    password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)

pct/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, HttpResponseBadRequest
from dashboard import models
from dashboard.models import movie, show, theatre, screen, User
from django.views.generic import DetailView, ListView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.contrib import messages
from main.models import TicketsForm,booking1
from django.contrib.auth.decorators import login_required
from .forms import logint,registertable
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View



# Create your views here.

def index(request):
    slider_images = movie.objects.raw('SELECT id,slideshow_image FROM dashboard_movie ORDER BY id DESC LIMIT 4')

    thumbnail_images = movie.objects.raw('SELECT id,thumbnail_image FROM dashboard_movie ORDER BY id DESC LIMIT 8')

    trailer = movie.objects.raw('SELECT id,trailer FROM dashboard_movie ORDER BY id DESC LIMIT 6')

    return render(request, 'main/index.html',
                  {'slider_images': slider_images, 'thumbnail_images': thumbnail_images, 'trailer': trailer})


class movies(ListView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-view.html'


class movie_detail_view(DetailView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-detail-view.html'


class movie_booking_theatre(DetailView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-booking-theatre.html'


class show_details(LoginRequiredMixin, DetailView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TicketsForm
        show_id = self.kwargs['pk']
        Show = show.objects.get(pk=show_id)
        context['tickets_booked'] = booking1.objects.filter(show=Show)
        return context

    context_object_name = 'show'
    model = models.show
    template_name = 'main/booking-page.html'


@login_required
def book_ticket(request, pk=None, id=None):
    data = TicketsForm(request.POST)
    Booking = data.save(commit=False)
    Show = show.objects.get(pk=pk)
    user = User.objects.get(pk=id)
    Booking.show = Show
    Booking.user = user

    if Booking.row_num == 0 or Booking.col_num == 0 or Booking.row_num > Show.screen.no_of_rows or Booking.col_num > Show.screen.no_of_columns:
        return HttpResponseBadRequest("Invalid ticket number")

    if not request.session.session_key:
        request.session.save()
    Booking.session = request.session.session_key

    try:
        existing_tix = booking1.objects.get(row_num=Booking.row_num, col_num=Booking.col_num, show=Show)
        if existing_tix.session == Booking.session and existing_tix.status == 1:
            if existing_tix.status == 1:
                existing_tix.delete()
            else:
                Booking = existing_tix
        else:
         return HttpResponseBadRequest("This ticket has already been reserved")
    except booking1.DoesNotExist:
        pass

    Booking.save()

    return redirect('main:booked', pk=pk)
    


class account(LoginRequiredMixin, DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        username = self.kwargs['user']
        u = get_object_or_404(User, pk=user_id)
        context['tickets_booked'] = booking1.objects.filter(user=u)
        if u.username == username:
            context['test'] = username
            return context

    context_object_name = 'user'
    model = models.User
    template_name = 'main/account.html'


class account_update(LoginRequiredMixin, UpdateView):
    context_object_name = 'user'
    model = models.User
    fields = ['username', 'first_name', 'last_name', 'email', ]
    template_name = 'main/account_form.html'
    success_url = reverse_lazy('main:index')


class account_delete(LoginRequiredMixin, DeleteView):
    context_object_name = 'user'
    model = models.User
    template_name = 'main/user_confirm_delete.html'
    success_url = reverse_lazy('main:logout')



def user_signup(request) :

    if request.method == 'POST':
      if (request.POST.get('username')) and request.POST.get('first_name') and request.POST.get(
            'Last_name') and request.POST.get('email') and request.POST.get('password') and request.POST.get(
            'confirm_password'):
        i=request.POST.get('username')
        em=request.POST.get('email')
        if User.objects.filter(username=i).exists():
            return render(request, "main/invalidus.html")
        if User.objects.filter(email=em).exists():
            return render(request, "main/invalidem.html")
        reg = User()
        reg.username=request.POST.get('username')
        reg.first_name=request.POST.get('first_name')
        reg.last_name=request.POST.get('Last_name')
        reg.email=request.POST.get('email')
        reg.password=request.POST.get('password')
        y = request.POST.get('confirm_password')
        username=request.POST.get('username')
        password=request.POST.get('password')

        if reg.password == y:
            reg.save()
            user = User.objects.filter(username=username, password=password).first()
            auth_login(request, user)
            redirect('main:account', pk=user.id, user=user.username)
            return redirect('main:index')

        else:
             return render(request,"main/invalidpw.html")
    form=registertable()
    return render(request, 'main/signup.html', {'form': form} )

def login(request):
    if request.method == 'POST':
        form = logint(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.filter(username=username, password=password).first()
            if user is not None:
              auth_login(request, user)
              redirect('main:account', pk=user.id, user=user.username)
              return redirect('main:index')
            else:
              return render(request,"main/invlog.html")
    else:
        form=logint()
        return render(request, "registration/login.html", context={'form': form})


def search(request):
    if request.method == 'POST':
        search_query = request.POST['search']

        if search_query:
            result = movie.objects.filter(
                Q(name__icontains=search_query) | Q(hero__icontains=search_query) | Q(heroine__icontains=search_query))

            if result:
                return render(request, 'main/search.html', {'results': result, 'search_query': search_query})
            else:
                messages.error(request, 'Sorry no results found')
        else:
            return HttpResponseRedirect('/')

    return render(request, 'main/search.html')


class booked(LoginRequiredMixin, DetailView):
    context_object_name = 'show'
    model = models.show
    template_name = 'main/confirm_movie.html'


def cancel_ticket(request, pk=None):
    Ticket = booking1.objects.get(pk=pk)
    Ticket.delete()
    return redirect('main:index')

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/login/')

pct/main/templates/main/account.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}

{% if test %}
<style>

.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-danger {
        font-weight: 700;
        border-radius: 2rem;
        width: 150px;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

    button:focus {
        outline: none !important;
    }

    h4 {
        letter-spacing: 3px;
        line-height : 32px;
        font-size: 18px;
    }



</style>



<div class="container">
    <h1>Profile</h1><br>
    <a href="{% url 'main:accounts-update' pk=user.id %}"><button class="btn btn-primary">Edit Profile</button></a>
    <a href="{% url 'main:accounts-delete' pk=user.id %}"><button class="btn btn-danger">Delete Profile</button></a>
</div>

<div class="container" id="profile" style="margin-top: 40px;margin-bottom: 30px;">
    <h4>User Name : <strong>{{ user.username }}</strong></h4>
    <h4>First Name : <strong>{{ user.first_name }}</strong></h4>
    <h4>Last Name : <strong>{{ user.last_name }}</strong></h4>
    <h4>Email : <strong>{{ user.email }}</strong></h4>
    <h4>Active Status : <strong>{{ user.is_active }}</strong></h4>
    <h4>Date Joined : <strong>{{ user.date_joined }}</strong></h4>

</div>


<div class="container">
    <h3><strong>Booked Tickets</strong></h3></br>
        <table class="table table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Created At</th>
                    <th>Movie</th>
                    <th>Theatre</th>
                      <th>Screen</th>
                      <th>Time</th>
                    <th>Row No</th>
                    <th>Col No</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for t in tickets_booked %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ t.created_at }}</td>
                    <td>{{ t.show.movie.name }}</td>
                    <td>{{ t.show.theatre.name }}</td>
                    <td>{{ t.show.screen.name }}</td>
                    <td>{{ t.show.time }}</td>
                      <td>{{ t.row_num }}</td>
                    <td>{{ t.col_num }}</td>
                    <td><a href="{% url 'main:cancel_ticket' pk=t.id  %}"><button class="btn btn-danger" style="width:70px;"> <i class="fas fa-times-circle"></i></button></a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
</div>


{% else %}

<div class="container" style="margin-top : 30px;margin-bottom:60px;">
    <img src="{% static 'image/404.png' %}" alt="404 page" class="img img-responsive center-block" />
</div>

{% endif %}

{% endblock %}

pct/main/templates/main/booking-page.html
{% extends 'main/layout.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    label {
        color: rgb(0, 0, 0);
        letter-spacing: 2px;
    }

    .form-control {
        width: 90%;
    }

    .btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

    .help-block {
        font-size: 16px !important;
    }

    .btn-danger {
        float: left;
        margin-left: -18px;
        margin-top: -10px;
        height: 20px;
        background-color: rgb(7, 7, 218);
        border: none;
    }

    .btn-danger:hover {
        background-color: rgb(122, 122, 241);
    }

    .payment {
        font-weight: 400;
        line-height: 27px;
        letter-spacing: 3px;
        text-align: center;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <div class="container">
                    <label class="btn btn-danger"><input type="checkbox" class="seats" value="1" disabled style="width:0px;"></label>
                <h3 style="position: absolute;margin-top : -10px;margin-left: 30px;"><strong>Booked Seats</strong></h3>
            </div></br></br>

            <div class="seatStructure txt-center" style="overflow-x:auto;">
                <table id="seatsBlock">
                    <tr>
                        {% with range=show.screen.no_of_rows %}
                        {% for i in i|rjust:range %}
                        <td style="padding-left : 25px;">{{ forloop.counter }}</td>
                        {% endfor %}
                        {% endwith %}
                    </tr>
                    {% with range=show.screen.no_of_columns  %}
                    {% for j in j|rjust:range %}
                    <tr>
                        <td style="padding-bottom : 25px;">{{ forloop.counter }}</td>
                        {% with range=show.screen.no_of_rows %}
                        {% for k in k|rjust:range %}
                        <td>{% for t in tickets_booked %}
                            {% if forloop.parentloop.counter == t.col_num and  forloop.parentloop.parentloop.counter == t.row_num %}
                            <label class="btn btn-danger">
                                <input type="checkbox" class="seats" value="{{ forloop.parentloop.counter }}" disabled
                                    style="width:0px;"></label>
                            {% endif %}
                            {% endfor %}
                        </td>
                        {% endfor %}
                        {% endwith %}
                    </tr>
                    {% endfor %}
                    {% endwith %}
                </table></br>
                <div class="jumbotron" style="width:90%;padding : 6px;">
                    <h3 style="margin-left : 40%;color:rgb(7, 7, 218);"><strong>SCREEN</strong></h3>
                </div>

            </div>

        </div>
        <div class="col-lg-6">

            <div class="jumbotron" style="width:90%;">
                <form action="{% url 'main:book-ticket' pk=show.id id=user.id %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p}}
                    </br><input type="submit" class="btn btn-primary" value="Submit" />
                    </br></br>
                    <h5 class="payment"><strong>NOTE* :</strong> Rs {{ show.price }} will be deducted from your linked
                        wallet</h5>
                </form>
            </div>


        </div>
    </div>
</div>



{% endblock %}

pct/main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <!--External Links-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  <script src="{%static 'js/bootstrap.min.js' %}"></script>

  <!-- custom style sheet -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>


<body style="background-color:rgb(255, 246, 246)">

    <nav class="navbar navbar-inverse navbar-static-top hidden-sm hidden-xs" id="navigation_bar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'main:index' %}" style="color: rgb(255, 255, 255);"><strong>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right " style="text-align: center;margin-right : 10px;">
            {% if user.is_authenticated %}
              <br>
              <li><a href="{% url 'main:accounts' pk=user.id user=user.username %}"><span class="glyphicon glyphicon-fire" style="color: white;"></span><strong>Welcome {{ user.username }}</strong></a></li>
          {% endif %}
          <li><a href="{% url 'main:movies' %}"><strong><span class="glyphicon glyphicon-fire" style="color: white;"></span>&nbsp;
                Movies</strong></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:logout' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Logout</strong></a></li>
          {% else %}
          <li><a href="{% url 'main:signup' %}"><strong><span class="glyphicon glyphicon-user"></span>&nbsp;Signup</strong></a></li>
          <li><a href="{% url 'login' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</strong></a></li>
          {% endif %}
            <form class="navbar-form navbar-right" action="{% url 'main:search' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie,Hero,Heroine" name="search" >
              </div>
              <button type="submit" class="btn btn-default"><strong>Submit</strong></button>
            </form>
          </ul>
        </div>
      </div>
    </nav>


    <!-- End of navbar -->


    <!--mobile navbar-->


    <div class="topnav" id="myTopnav" style="margin-bottom:20px;">
      <div class="hidden-lg hidden-md">

        <a href="#"><strong><span id="first_letter">I</span>O Screen</strong></a>
        <a href="#" style="color: rgb(255,255,255);"><i class="far fa-newspaper" style="font-size: 20px;"></i>
          &nbsp;<
        <a href="#" style="color: rgb(255,255,255);"><i class="fab fa-blogger-b" style="font-size: 20px;"></i>
          &nbsp;<strong><span id="first_letter">B</span>log</strong></a>

        <form action="">
          <input type="text" class="form-control" placeholder="Search">
          <button type="submit" class="btn btn-primary" id="search_submit" style="margin-top : 10px;">Submit</button>
        </form>

        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div>

    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>


    <!--end of mobile navbar-->


    {% block content %}
    {% endblock %}

    <div class="container-fluid" style="background-color: rgb(0,0,0);padding-top: 40px;">
        <div class="row">
          <div class="col-lg-6" style="text-align: center;">


          </div>

        </div>

      </div>

    </body>

    </html>

pct/main/templates/main/layout1.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>welcome</title>
  <!--External Links-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  <script src="{%static 'js/bootstrap.min.js' %}"></script>

  <!-- custom style sheet -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>





  <!-- Rest of your content -->
    <!-- Your navigation bar content -->


<body style="background-color:rgb(255, 246, 246)">

    <nav class="navbar navbar-inverse navbar-static-top hidden-sm hidden-xs" id="navigation_bar">
      <div class="container-fluid">
        <div class="navbar-header">
<!--          <a class="navbar-brand" href="{% url 'main:index' %}" style="color: rgb(255, 255, 255);"><strong>-->
<!--        </div>-->
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right " style="text-align: center;margin-right : 10px;">
<!--            {% if user.is_authenticated %}-->

<!--          <li><a href="{% url 'main:accounts' pk=user.id user=user.username %}"><strong>Welcome {{ user.username }}</strong></a></li>-->
          {% endif %}
<!--          <li><a href="{% url 'main:movies' %}"><strong><span class="glyphicon glyphicon-fire" style="color: red;"></span>&nbsp;-->
<!--                Movies</strong></a></li>-->
<!--          {% if user.is_authenticated %}-->
<!--          <li><a href="{% url 'logout' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Logout</strong></a></li>-->
<!--          {% else %}-->
<!--          <li><a href="{% url 'main:signup' %}"><strong><span class="glyphicon glyphicon-user"></span>&nbsp;Signup</strong></a></li>-->
<!--          <li><a href="{% url 'login' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</strong></a></li>-->
          {% endif %}
<!--            <form class="navbar-form navbar-right" action="{% url 'main:search' %}" method="POST">-->
              {% csrf_token %}
<!--              <div class="form-group">-->
<!--                <input type="text" class="form-control" placeholder="Movie,Hero,Heroine" name="search" >-->
<!--              </div>-->
<!--              <button type="submit" class="btn btn-default"><strong>Submit</strong></button>-->
<!--            </form>-->
          </ul>
        </div>
      </div>
    </nav>


    <!-- End of navbar -->


    <!--mobile navbar-->


    <div class="topnav" id="myTopnav" style="margin-bottom:20px;">
      <div class="hidden-lg hidden-md">

        <a href="#"><strong><span id="first_letter">I</span>O Screen</strong></a>
        <a href="#" style="color: rgb(255,255,255);"><i class="far fa-newspaper" style="font-size: 20px;"></i>
          &nbsp;<
        <a href="#" style="color: rgb(255,255,255);"><i class="fab fa-blogger-b" style="font-size: 20px;"></i>
          &nbsp;<strong><span id="first_letter">B</span>log</strong></a>

        <form action="">
          <input type="text" class="form-control" placeholder="Search">
          <button type="submit" class="btn btn-primary" id="search_submit" style="margin-top : 10px;">Submit</button>
        </form>

        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div>

    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>


    <!--end of mobile navbar-->


    {% block content %}
    {% endblock %}

    <div class="container-fluid" style="background-color: rgb(0,0,0);padding-top: 40px;">
        <div class="row">
          <div class="col-lg-6" style="text-align: center;">


          </div>

        </div>

      </div>

    </body>

    </html>

pct/main/templates/main/movie-booking-theatre.html
{% extends 'main/layout.html' %}

{% block content %}

<style>
    .btn-default {
        border: 1px solid rgb(24, 100, 5);
    }

    .slideshow_image {
        box-shadow: 0px 4px 8px 0px rgb(0,0,0);
        border-radius: 20px;
    }
</style>

<div class="container-fluid" style="margin-top: -20px;">
    <img src="{{ movie.slideshow_image.url }}" alt="{{ movie.slideshow_image }}" height="350px;" width="95%"
        class="center-block slideshow_image" />

    <h2 style="text-align: center;color: rgb(0,0,0);margin-top : 20px;"><strong>Confirm Your Show For <span style="color : rgb(255,0,0);">{{ movie.name|upper}}</span> </strong></h2>
</div>

<div class="container" style="margin-bottom: 20px;">
    {% for current in movie.show_movie.all %}
    {% ifchanged %}
    <h4 style="margin-top : 20px;margin-bottom: 20px;"><strong>{{ current.theatre.name }}, {{current.screen.name}} {{ current.date }}</strong>
    </h4>
    {% endifchanged %}
    <a href="{% url 'main:movie-booking' pk=current.id %}"><button class="btn btn-default" style="display: inline-block;margin-left : 15px;">{{ current.time }}</button></a>
    {% endfor %}
</div>
{% endblock %}