pct/main/urls.py
from django.urls import path,include,re_path
from main import views
from .views import login,LogoutView
app_name = 'main'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('',views.user_signup,name="signup"),
    path('movies/', views.movies.as_view(), name='movies'),
    path('search/', views.search, name='search'),
    path('login/', views.login),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/<int:pk>/<str:user>/', views.account.as_view(), name='account'),
    re_path(r'^accounts/(?P<pk>\d+)/(?P<user>[\w.@+-]+)/$', views.account.as_view(), name="accounts"),
    re_path(r'^accounts-update/(?P<pk>\d+)/',views.account_update.as_view(),name="accounts-update"),
    re_path(r'^accounts-delete/(?P<pk>\d+)/',views.account_delete.as_view(),name="accounts-delete"),
    re_path(r'^movie-detail/(?P<pk>\d+)/',views.movie_detail_view.as_view(),name="movie-detail-view"),
    re_path(r'^theatre-list/(?P<pk>\d+)/',views.movie_booking_theatre.as_view(),name="movie-booking-theatre"),
    re_path(r'^booking/(?P<pk>\d+)/',views.show_details.as_view(),name="movie-booking"),
    re_path(r'^book-ticket/(?P<pk>\d+)/(?P<id>\d+)',views.book_ticket,name="book-ticket"),
    re_path(r'^booked/(?P<pk>\d+)/',views.booked.as_view(),name="booked"),
    re_path(r'^cancel/(?P<pk>\d+)/',views.cancel_ticket,name="cancel_ticket"),
]

pct/pct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='main'),
    path('manager/',include('login.urls'),name='manager'),
    path('manager/dashboard/',include('dashboard.urls'),name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'),name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pct/main/models.py
from django.db import models
from django.forms import ModelForm
from dashboard.models import show
from django.contrib.auth.models import User



TICKET_STATUS_CHOICES=(
    (1,'AVAILABLE'),
    (2,'BLOCKED'),
    (3,'BOOKED')
)

class booking1(models.Model):

    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField(null=False)
    phonenumber=models.IntegerField(default=None)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    row_num = models.PositiveSmallIntegerField(null=False, blank=False)
    col_num = models.PositiveSmallIntegerField(null=False, blank=False)
    show = models.ForeignKey(show, related_name="booking1_movie", null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="booking1_show", null=False, default=None, on_delete=models.CASCADE)
    status = models.IntegerField(choices=TICKET_STATUS_CHOICES, default=1)
    session = models.CharField(blank=False, null=False, max_length=200)

    def __str__(self):
        return str(self.phonenumber)
    class Meta:
        unique_together=('show','row_num','col_num')



class TicketsForm(ModelForm):
    class Meta:
        model = booking1
        fields = ['name','age','phonenumber','col_num','row_num',]

pct/main/forms.py
from django import forms

# username=models.CharField(max_length=20)
#     first_name=models.CharField(max_length=20)
#     last_name=models.CharField(max_length=20)
#     email=models.EmailField()
#     password=models.CharField(max_length=20)
class registertable(forms.Form):
    username=forms.CharField(min_length=6,max_length=15)
    first_name=forms.CharField(min_length=6,max_length=15)
    Last_name=forms.CharField(min_length=6,max_length=15)
    email=forms.EmailField()
    password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)
    confirm_password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)

class logint(forms.Form):
    username=forms.CharField(min_length=6,max_length=15)
    password=forms.CharField(min_length=8,max_length=16,widget=forms.PasswordInput)

pct/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, HttpResponseBadRequest
from dashboard import models
from dashboard.models import movie, show, theatre, screen, User
from django.views.generic import DetailView, ListView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.contrib import messages
from main.models import TicketsForm,booking1
from django.contrib.auth.decorators import login_required
from .forms import logint,registertable
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View



# Create your views here.

def index(request):
    slider_images = movie.objects.raw('SELECT id,slideshow_image FROM dashboard_movie ORDER BY id DESC LIMIT 4')

    thumbnail_images = movie.objects.raw('SELECT id,thumbnail_image FROM dashboard_movie ORDER BY id DESC LIMIT 8')

    trailer = movie.objects.raw('SELECT id,trailer FROM dashboard_movie ORDER BY id DESC LIMIT 6')

    return render(request, 'main/index.html',
                  {'slider_images': slider_images, 'thumbnail_images': thumbnail_images, 'trailer': trailer})


class movies(ListView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-view.html'


class movie_detail_view(DetailView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-detail-view.html'


class movie_booking_theatre(DetailView):
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-booking-theatre.html'


class show_details(LoginRequiredMixin, DetailView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TicketsForm
        show_id = self.kwargs['pk']
        Show = show.objects.get(pk=show_id)
        context['tickets_booked'] = booking1.objects.filter(show=Show)
        return context

    context_object_name = 'show'
    model = models.show
    template_name = 'main/booking-page.html'


@login_required
def book_ticket(request, pk=None, id=None):
    data = TicketsForm(request.POST)
    Booking = data.save(commit=False)
    Show = show.objects.get(pk=pk)
    user = User.objects.get(pk=id)
    Booking.show = Show
    Booking.user = user

    if Booking.row_num == 0 or Booking.col_num == 0 or Booking.row_num > Show.screen.no_of_rows or Booking.col_num > Show.screen.no_of_columns:
        return HttpResponseBadRequest("Invalid ticket number")

    if not request.session.session_key:
        request.session.save()
    Booking.session = request.session.session_key

    try:
        existing_tix = booking1.objects.get(row_num=Booking.row_num, col_num=Booking.col_num, show=Show)
        if existing_tix.session == Booking.session and existing_tix.status == 1:
            if existing_tix.status == 1:
                existing_tix.delete()
            else:
                Booking = existing_tix
        else:
         return HttpResponseBadRequest("This ticket has already been reserved")
    except booking1.DoesNotExist:
        pass

    Booking.save()

    return redirect('main:booked', pk=pk)
    


class account(LoginRequiredMixin, DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        username = self.kwargs['user']
        u = get_object_or_404(User, pk=user_id)
        context['tickets_booked'] = booking1.objects.filter(user=u)
        if u.username == username:
            context['test'] = username
            return context

    context_object_name = 'user'
    model = models.User
    template_name = 'main/account.html'


class account_update(LoginRequiredMixin, UpdateView):
    context_object_name = 'user'
    model = models.User
    fields = ['username', 'first_name', 'last_name', 'email', ]
    template_name = 'main/account_form.html'
    success_url = reverse_lazy('main:index')


class account_delete(LoginRequiredMixin, DeleteView):
    context_object_name = 'user'
    model = models.User
    template_name = 'main/user_confirm_delete.html'
    success_url = reverse_lazy('main:logout')



def user_signup(request) :

    if request.method == 'POST':
      if (request.POST.get('username')) and request.POST.get('first_name') and request.POST.get(
            'Last_name') and request.POST.get('email') and request.POST.get('password') and request.POST.get(
            'confirm_password'):
        i=request.POST.get('username')
        em=request.POST.get('email')
        if User.objects.filter(username=i).exists():
            return render(request, "main/invalidus.html")
        if User.objects.filter(email=em).exists():
            return render(request, "main/invalidem.html")
        reg = User()
        reg.username=request.POST.get('username')
        reg.first_name=request.POST.get('first_name')
        reg.last_name=request.POST.get('Last_name')
        reg.email=request.POST.get('email')
        reg.password=request.POST.get('password')
        y = request.POST.get('confirm_password')
        username=request.POST.get('username')
        password=request.POST.get('password')

        if reg.password == y:
            reg.save()
            user = User.objects.filter(username=username, password=password).first()
            auth_login(request, user)
            redirect('main:account', pk=user.id, user=user.username)
            return redirect('main:index')

        else:
             return render(request,"main/invalidpw.html")
    form=registertable()
    return render(request, 'main/signup.html', {'form': form} )

def login(request):
    if request.method == 'POST':
        form = logint(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.filter(username=username, password=password).first()
            if user is not None:
              auth_login(request, user)
              redirect('main:account', pk=user.id, user=user.username)
              return redirect('main:index')
            else:
              return render(request,"main/invlog.html")
    else:
        form=logint()
        return render(request, "registration/login.html", context={'form': form})


def search(request):
    if request.method == 'POST':
        search_query = request.POST['search']

        if search_query:
            result = movie.objects.filter(
                Q(name__icontains=search_query) | Q(hero__icontains=search_query) | Q(heroine__icontains=search_query))

            if result:
                return render(request, 'main/search.html', {'results': result, 'search_query': search_query})
            else:
                messages.error(request, 'Sorry no results found')
        else:
            return HttpResponseRedirect('/')

    return render(request, 'main/search.html')


class booked(LoginRequiredMixin, DetailView):
    context_object_name = 'show'
    model = models.show
    template_name = 'main/confirm_movie.html'


def cancel_ticket(request, pk=None):
    Ticket = booking1.objects.get(pk=pk)
    Ticket.delete()
    return redirect('main:index')

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/login/')

pct/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <!--External Links-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  <script src="{%static 'js/bootstrap.min.js' %}"></script>

  <!-- custom style sheet -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>

<body onload="showDivs(1)" style="background-color:rgb(255, 246, 246)">

  <nav class="navbar navbar-inverse navbar-static-top hidden-sm hidden-xs" id="navigation_bar">
    <div class="container-fluid">
      <div class="navbar-header">

      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right " style="text-align: center;margin-right : 10px;">
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:accounts' pk=user.id user=user.username %}"><strong><span class="glyphicon glyphicon-fire" style="color: white"></span>Welcome {{ user.username }}</strong></a></li>
          {% endif %}
          <li><a href="{% url 'main:movies' %}"><strong><span class="glyphicon glyphicon-fire" style="color: white"></span>&nbsp;
                Movies</strong></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:logout' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Logout</strong></a></li>
          {% else %}
          <li><a href="{% url 'main:signup' %}"><strong><span class="glyphicon glyphicon-user"></span>&nbsp;Signup</strong></a></li>
          <li><a href="{% url 'login' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</strong></a></li>
          {% endif %}
          <form class="navbar-form navbar-right" action="{% url 'main:search' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Movie,Hero,Heroine" name="search">
            </div>
            <button type="submit" class="btn btn-default"><strong>Submit</strong></button>
          </form>
        </ul>
      </div>
    </div>
  </nav>


  <!-- End of navbar -->


  <!--mobile navbar-->


  <div class="topnav" id="myTopnav" style="margin-bottom:20px;">
    <div class="hidden-lg hidden-md">

      <a href="#"><strong><span id="first_letter">I</span>O Screen</strong></a>
      <a href="#" style="color: rgb(255,255,255);"><i class="far fa-newspaper" style="font-size: 20px;"></i>
        &nbsp;<strong><span id="first_letter">P</span>rojects</strong></a>
      <a href="#" style="color: rgb(255,255,255);"><i class="fab fa-blogger-b" style="font-size: 20px;"></i>
        &nbsp;<strong><span id="first_letter">B</span>log</strong></a>

      <form action="">
        <input type="text" class="form-control" placeholder="Search">
        <button type="submit" class="btn btn-primary" id="search_submit" style="margin-top : 10px;">Submit</button>
      </form>

      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </div>

  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }

    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
      showDivs(slideIndex += n);
    }

    function showDivs(n) {
      var i;
      var x = document.getElementsByClassName("mySlides");
      if (n > x.length) {
        slideIndex = 1
      }
      if (n < 1) {
        slideIndex = x.length
      }
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      x[slideIndex - 1].style.display = "block";

    }
  </script>




  <div class="container" style="margin-top: -10px;">
    {% for image in slider_images %}

    <a href="{% url 'main:movie-detail-view' pk=image.id %}"><img class="mySlides center-block" src="{{ image.slideshow_image.url }}" alt="{{ image.slideshow_image }}"
      style="width:100%;height : 450px;"></a>

    <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
    <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>

    {% endfor %}
  </div>

  <div class="container background-heading">
    <h3 id="center-heading"><strong>NOW SHOWING</strong></h3>
  </div>

  <div class="container" style="margin-top : 30px;">
    <div class="row">
      {% for image in thumbnail_images %}
      <div class="col-lg-3 col-md-3" style="margin-bottom : 30px;">
        <div class="card">
          <a href="{% url 'main:movie-detail-view' pk=image.id %}"><img src="{{ image.thumbnail_image.url }}" alt="{{ image.thumbnail_image }}"
            style="width:100%;height: 300px;border-radius: 10px;"></a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="container background-heading">
    <h3 id="center-heading"><strong>LATEST TRAILERS</strong></h3>
  </div>

  <div class="container" style="margin-top : 30px;">
    <div class="row">
      {% for tr in trailer %}
      <div class="col-lg-4" style="margin-bottom : 30px;">
        <iframe width="100%" height="250px" src="https://www.youtube.com/embed/{{tr.trailer}}" frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {{tr.name}}: <a href="{{tr.trailer}}">click here</a>
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="container-fluid" style="background-color: rgb(0,0,0);padding-top: 40px;">
    <div class="row">
      <div class="col-lg-6" style="text-align: center;">
        <a class="footer-brand" href="#" style="color: rgb(255, 255, 255);"><strong>

      </div>

    </div>
  </div>

</body>

</html>

pct/templates/main/search.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

{% if messages %}

<div class="container" style="margin-bottom:390px;">
    {% for m in messages %}
    <div class="alert alert-danger">
            <strong>{{m}}</strong>
          </div>
    {% endfor %}
</div>

{% endif %}

{% if results %}

<div class="container" style="margin-top : 30px;margin-bottom: 180px;">
    <h3 style="letter-spacing : 3px;"><strong>Showing results for <span style="color: rgb(255,0,0);">{{ search_query|upper }}</span></strong></h3></br></br>
        <div class="row">
          {% for r in results %}
          <div class="col-lg-3 col-md-3" style="margin-bottom : 30px;">
            <div class="card">
              <a href="{% url 'main:movie-detail-view' pk=r.id %}"><img src="{{ r.thumbnail_image.url }}"
                style="width:100%;height: 300px;border-radius: 10px;"></a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

{% endif %}

{% endblock %}